### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#29]
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.bifan.txtreaderlib.main.ParagraphData.getParaStartCharIndex(ParagraphData.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.getProgress(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderView$1$1.run(TxtReaderView.java)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5491)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:961)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by bifan-wei** [comment]
无法重现，对段落数据长度进行了相应的判断处理
