### ISSUE TITLE
用户使用出现：java.lang.IllegalArgumentException: width must be > 0

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#33]
java.lang.IllegalArgumentException: width must be > 0
	at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:378)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
	at com.bifan.txtreaderlib.utils.TxtBitmapUtil.createBitmap(Unknown Source)
	at com.bifan.txtreaderlib.tasks.TxtConfigInitTask.Run(Unknown Source)
	at com.bifan.txtreaderlib.tasks.FileDataLoadTask.Run(Unknown Source)
	at com.bifan.txtreaderlib.tasks.TxtFileLoader.load(Unknown Source)
	at com.bifan.txtreaderlib.tasks.TxtFileLoader.load(Unknown Source)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

**Comment by bifan-wei** [comment]
兄地，你这样贴个日志我很懵逼啊，如何重现问题，重现不了我也没啥办法啊

**Comment by skyLiao** [comment]
用户使用出现的问题，没法知道场景。只能根据堆栈分析修复了

**Comment by bifan-wei** [comment]
重现不了我也没办法了，我这边用这个库几个月，目前没发现什么问题
