### ISSUE TITLE
用户使用出现：java.lang.NullPointerException: Attempt to invoke interface method 'int com.bifan.txtreaderlib.interfaces.IParagraphData.getCharNum()'

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#34]
java.lang.NullPointerException: Attempt to invoke interface method 'int com.bifan.txtreaderlib.interfaces.IParagraphData.getCharNum()' on a null object reference
	at com.bifan.txtreaderlib.main.TxtReaderView.loadFromProgress(TxtReaderView.java)
	at com.bifan.txtreaderlib.ui.HwTxtPlayActivity$10.onTouch(HwTxtPlayActivity.java)
	at android.view.View.dispatchTouchEvent(View.java:10206)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2398)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:471)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1864)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3227)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:425)
	at android.view.View.dispatchPointerEvent(View.java:10446)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5421)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5220)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4677)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4737)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4696)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4865)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4704)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4922)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4677)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4737)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4696)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4704)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4677)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7398)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7372)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7315)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7574)
	at android.view.ViewRootImpl$ColorWindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9129)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:328)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6802)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by bifan-wei** [comment]
无法重现
