### ISSUE TITLE
用户使用出现：java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setColor(int)' on a null object reference

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#35]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setColor(int)' on a null object reference
	at com.bifan.txtreaderlib.utils.TxtBitmapUtil.createHorizontalPage(Unknown Source)
	at com.bifan.txtreaderlib.tasks.BitmapProduceTask.Run(Unknown Source)
	at com.bifan.txtreaderlib.tasks.DrawPrepareTask.Run(Unknown Source)
	at com.bifan.txtreaderlib.tasks.TxtPageLoadTask.Run(Unknown Source)
	at com.bifan.txtreaderlib.tasks.TxtConfigInitTask.Run(Unknown Source)
	at com.bifan.txtreaderlib.tasks.FileDataLoadTask.Run(Unknown Source)
	at com.bifan.txtreaderlib.tasks.TxtFileLoader.load(Unknown Source)
	at com.bifan.txtreaderlib.tasks.TxtFileLoader.load(Unknown Source)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:760)

**Comment by bifan-wei** [comment]
无法重现
