### ISSUE TITLE
用户使用出现：java.lang.NullPointerException: Attempt to invoke interface method 'int com.bifan.txtreaderlib.interfaces.IParagraphData.getParagraphNum()' on a null object reference

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#36]
java.lang.NullPointerException: Attempt to invoke interface method 'int com.bifan.txtreaderlib.interfaces.IParagraphData.getParagraphNum()' on a null object reference
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.getProgress(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.onPageProgress(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView$DataLoadListener$1.run(TxtReaderBaseView.java)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5689)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by bifan-wei** [comment]
无法重现
