### ISSUE TITLE
用户使用出现：java.lang.NullPointerException 	at com.bifan.txtreaderlib.main.TxtReaderBaseView.getProgress(TxtReaderBaseView.java)

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#37]
java.lang.NullPointerException
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.getProgress(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderView$1$1.run(TxtReaderView.java)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:177)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
	at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by bifan-wei** [comment]
无法重现
