### ISSUE TITLE
用户使用出现：java.lang.NullPointerException: Attempt to read from field 'android.widget.SeekBar com.bifan.txtreaderlib.ui.HwTxtPlayActivity$MenuHolder.mSeekBar' on a null object reference

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#40]
java.lang.NullPointerException: Attempt to read from field 'android.widget.SeekBar com.bifan.txtreaderlib.ui.HwTxtPlayActivity$MenuHolder.mSeekBar' on a null object reference
	at com.bifan.txtreaderlib.ui.HwTxtPlayActivity$12.onCurrentPage(HwTxtPlayActivity.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.onProgressCallBack(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.onPageProgress(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView$DataLoadListener$1.run(TxtReaderBaseView.java)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6337)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by bifan-wei** [comment]
无法重现
