### ISSUE TITLE
用户使用出现：java.lang.NullPointerException: Attempt to read from field 'int com.bifan.txtreaderlib.main.PageParam.LinePadding' on a null object reference

### ISSUE THREAD

**Issue by skyLiao** [bifan-wei/HwTxtReader#41]
java.lang.NullPointerException: Attempt to read from field 'int com.bifan.txtreaderlib.main.PageParam.LinePadding' on a null object reference
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.findCharByPosition(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.onPressSelectText(TxtReaderBaseView.java)
	at com.bifan.txtreaderlib.main.TxtReaderBaseView.onLongPress(TxtReaderBaseView.java)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
	at android.view.GestureDetector.-wrap0(GestureDetector.java)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6342)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by bifan-wei** [comment]
无法重现
