### ISSUE TITLE
Android Pie 崩溃，下面是log

### ISSUE THREAD

**Issue by just-for-krystal** [bifan-wei/HwTxtReader#56]
2019-01-09 18:39:32.329 19608-19608/com.example.kryst.reader E/TxtReaderBaseView: onShowPress ,CurrentMode:Normal
2019-01-09 18:39:32.400 19608-19608/com.example.kryst.reader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kryst.reader, PID: 19608
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipPath(Canvas.java:1007)
        at com.bifan.txtreaderlib.main.NormalPageDrawer.drawPageNextBottomPage(NormalPageDrawer.java:49)
        at com.bifan.txtreaderlib.main.TxtReaderView.drawPageNextBottomPage(TxtReaderView.java:98)
        at com.bifan.txtreaderlib.main.TxtReaderView.drawLineText(TxtReaderView.java:77)
        at com.bifan.txtreaderlib.main.TxtReaderBaseView.onDraw(TxtReaderBaseView.java:99)
        at android.view.View.draw(View.java:20211)
        at android.view.View.updateDisplayListIfDirty(View.java:19086)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19046)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19046)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19046)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19046)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19046)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19046)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3327)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3124)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2493)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7208)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
        at android.view.Choreographer.doCallbacks(Choreographer.java:816)
        at android.view.Choreographer.doFrame(Choreographer.java:751)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by bifan-wei** [comment]
这就很尴尬了，没有pie系统的测试机，后面迟点再测试看吧

**Comment by bifan-wei** [comment]
找了台9.0的手机，没有发现这个问题，还出现这个问题的，麻烦说一声怎么出现的

**Comment by swillk** [comment]
targetSdkVersion 27 可以解决问题
