### ISSUE TITLE
TxtReaderView设置字体大小时崩溃

### ISSUE THREAD

**Issue by firechun** [bifan-wei/HwTxtReader#88]
private fun init() {
        TxtConfig.saveIsOnVerticalPageMode(this, false)
        TxtConfig.saveIsShowSpecialChar(this, false)
        //这一行时程序崩溃
        binding.bookView.textSize = 50
    }
错误信息：
     Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.bifan.txtreaderlib.main.PageParam.PageWidth' on a null object reference
        at com.bifan.txtreaderlib.tasks.TxtConfigInitTask.Run(TxtConfigInitTask.java:34)
        at com.bifan.txtreaderlib.main.TxtReaderView.Reload(TxtReaderView.java:236)
        at com.bifan.txtreaderlib.main.TxtReaderView.setTextSize(TxtReaderView.java:246)
        at com.firechun.myreader.activity.ReaderActivity.init(ReaderActivity.kt:26)
        at com.firechun.myreader.activity.ReaderActivity.onCreate(ReaderActivity.kt:19)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by bifan-wei** [comment]
问题已修复 [更新提交如下](https://github.com/bifan-wei/HwTxtReader/commit/d2e3c1db4172006116be1dca522ef1cfd6e83be8)
